### ISSUE TITLE
[Bug] Internal Server Error

### ISSUE THREAD

**Issue by Sahil2004** [wweverma1/github-readme-codeforces-stats#17]
When I do it for my profile https://codeforces-stats-api.herokuapp.com/stats?username=sahilgarg&theme=1 it is giving me internal server error.
![image](https://user-images.githubusercontent.com/40143545/202536795-678a83eb-e821-498a-a9f0-c1d6a44a85a9.png)

**Comment by wweverma1** [comment]
Hi, @Sahil2004 this error is coming up since I've exceeded the free dyno usage provided by Heroku and therefore the app has been shut down for now. 
However, Feel free to clone the project and test it on your local machine. 

To set up the project on your local machine you can use the commands given below-

- Install required packages
`pip install -r requirements.txt`

- Start Virtual Environment
`source venv/bin/activate`

- Start the Server
`python app.py`

Then send this request to your local server address-
`<local-server-address>/stats?username=sahilgarg&theme=1`

Regards,
Aditya Verma
