### ISSUE TITLE
Heroku: Application error

### ISSUE THREAD

**Issue by AprilNEA** [wweverma1/github-readme-codeforces-stats#18]
```
Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail
```

This seems to have stopped working on HeroKu

**Comment by wweverma1** [comment]
Hi, @AprilNEA this error is coming up since I've exceeded the free dyno usage provided by Heroku and therefore the app has been shut down for now.
However, Feel free to clone the project and test it on your local machine.

To set up the project on your local machine you can use the commands given below-

- Install required packages
`pip install -r requirements.txt`

- Start Virtual Environment
`source venv/bin/activate`

- Start the Server
`python app.py`

Then send this request to your local server address-
`<local-server-address>/stats?username=<your-codeforces-username>&theme=1`

Regards,
Aditya Verma
